# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vladislav/aipps

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vladislav/aipps

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vladislav/aipps/CMakeFiles /home/vladislav/aipps/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vladislav/aipps/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lab_Rab_1

# Build rule for target.
Lab_Rab_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lab_Rab_1
.PHONY : Lab_Rab_1

# fast build rule for target.
Lab_Rab_1/fast:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/build
.PHONY : Lab_Rab_1/fast

#=============================================================================
# Target rules for targets named api1

# Build rule for target.
api1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 api1
.PHONY : api1

# fast build rule for target.
api1/fast:
	$(MAKE) -f CMakeFiles/api1.dir/build.make CMakeFiles/api1.dir/build
.PHONY : api1/fast

#=============================================================================
# Target rules for targets named api2

# Build rule for target.
api2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 api2
.PHONY : api2

# fast build rule for target.
api2/fast:
	$(MAKE) -f CMakeFiles/api2.dir/build.make CMakeFiles/api2.dir/build
.PHONY : api2/fast

src/CharacterHandler.o: src/CharacterHandler.cpp.o
.PHONY : src/CharacterHandler.o

# target to build an object file
src/CharacterHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/CharacterHandler.cpp.o
.PHONY : src/CharacterHandler.cpp.o

src/CharacterHandler.i: src/CharacterHandler.cpp.i
.PHONY : src/CharacterHandler.i

# target to preprocess a source file
src/CharacterHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/CharacterHandler.cpp.i
.PHONY : src/CharacterHandler.cpp.i

src/CharacterHandler.s: src/CharacterHandler.cpp.s
.PHONY : src/CharacterHandler.s

# target to generate assembly for a file
src/CharacterHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/CharacterHandler.cpp.s
.PHONY : src/CharacterHandler.cpp.s

src/ConsonantStrategy.o: src/ConsonantStrategy.cpp.o
.PHONY : src/ConsonantStrategy.o

# target to build an object file
src/ConsonantStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/api1.dir/build.make CMakeFiles/api1.dir/src/ConsonantStrategy.cpp.o
.PHONY : src/ConsonantStrategy.cpp.o

src/ConsonantStrategy.i: src/ConsonantStrategy.cpp.i
.PHONY : src/ConsonantStrategy.i

# target to preprocess a source file
src/ConsonantStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/api1.dir/build.make CMakeFiles/api1.dir/src/ConsonantStrategy.cpp.i
.PHONY : src/ConsonantStrategy.cpp.i

src/ConsonantStrategy.s: src/ConsonantStrategy.cpp.s
.PHONY : src/ConsonantStrategy.s

# target to generate assembly for a file
src/ConsonantStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/api1.dir/build.make CMakeFiles/api1.dir/src/ConsonantStrategy.cpp.s
.PHONY : src/ConsonantStrategy.cpp.s

src/FlyweightFactory.o: src/FlyweightFactory.cpp.o
.PHONY : src/FlyweightFactory.o

# target to build an object file
src/FlyweightFactory.cpp.o:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/FlyweightFactory.cpp.o
.PHONY : src/FlyweightFactory.cpp.o

src/FlyweightFactory.i: src/FlyweightFactory.cpp.i
.PHONY : src/FlyweightFactory.i

# target to preprocess a source file
src/FlyweightFactory.cpp.i:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/FlyweightFactory.cpp.i
.PHONY : src/FlyweightFactory.cpp.i

src/FlyweightFactory.s: src/FlyweightFactory.cpp.s
.PHONY : src/FlyweightFactory.s

# target to generate assembly for a file
src/FlyweightFactory.cpp.s:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/FlyweightFactory.cpp.s
.PHONY : src/FlyweightFactory.cpp.s

src/VowelStrategy.o: src/VowelStrategy.cpp.o
.PHONY : src/VowelStrategy.o

# target to build an object file
src/VowelStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/api2.dir/build.make CMakeFiles/api2.dir/src/VowelStrategy.cpp.o
.PHONY : src/VowelStrategy.cpp.o

src/VowelStrategy.i: src/VowelStrategy.cpp.i
.PHONY : src/VowelStrategy.i

# target to preprocess a source file
src/VowelStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/api2.dir/build.make CMakeFiles/api2.dir/src/VowelStrategy.cpp.i
.PHONY : src/VowelStrategy.cpp.i

src/VowelStrategy.s: src/VowelStrategy.cpp.s
.PHONY : src/VowelStrategy.s

# target to generate assembly for a file
src/VowelStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/api2.dir/build.make CMakeFiles/api2.dir/src/VowelStrategy.cpp.s
.PHONY : src/VowelStrategy.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Lab_Rab_1.dir/build.make CMakeFiles/Lab_Rab_1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Lab_Rab_1"
	@echo "... api1"
	@echo "... api2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/CharacterHandler.o"
	@echo "... src/CharacterHandler.i"
	@echo "... src/CharacterHandler.s"
	@echo "... src/ConsonantStrategy.o"
	@echo "... src/ConsonantStrategy.i"
	@echo "... src/ConsonantStrategy.s"
	@echo "... src/FlyweightFactory.o"
	@echo "... src/FlyweightFactory.i"
	@echo "... src/FlyweightFactory.s"
	@echo "... src/VowelStrategy.o"
	@echo "... src/VowelStrategy.i"
	@echo "... src/VowelStrategy.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

